config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  get 'home',           to: 'pages#home'
  get 'about',          to: 'pages#about'
  get 'contact',        to: 'pages#contact'
  get 'event-tracker',  to: 'pages#event_tracker'

  resources :people
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, :main_image, :thumb_image, presence: true
    
    after_initialize :set_defaults

    def set_defaults
        self.main_image ||= "http://placeimg.com/600/400/nature"
        self.thumb_image ||= "http://placeimg.com/350/200/nature"
    end
end

app/models/person.rb
class Person < ApplicationRecord
    validates :first_name, :last_name, :main_image, :thumb_image, presence: true

    after_initialize :set_defaults

    def set_defaults
        self.main_image ||= "http://placeimg.com/600/400/nature"
        self.thumb_image ||= "http://placeimg.com/350/200/nature"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :details, :day, :month, :year)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def event_tracker
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.text_field :day %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.text_field :month %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<% @events.each do |event| %>
  <p><%= link_to event.title, event_path(event) %></p>
  <p><%="#{event.day}-#{event.month}-#{event.year}" %></p>
  <%= image_tag event.thumb_image %>
<% end %>


<br>

<%= link_to 'New Event', new_event_path %>
<%= link_to "Event Tracker", event_tracker_path %>
<%= link_to "Home", root_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @event.details %>
</p>

<%= image_tag @event.main_image %>


<p>
  <strong>Day:</strong>
  <%= @event.day %>
</p>

<p>
  <strong>Month:</strong>
  <%= @event.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @event.year %>
</p>


<br>

<%= link_to 'Edit Event', edit_event_path(@event) %> |
<%= link_to "Delete Event", event_path(@event), method: :delete, data: { confirm: "Are you sure you want to delete the person?" } %> |
<%= link_to 'Back', events_path %> |
<%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MainApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<%= link_to "Home", root_path %>

app/views/pages/contact.html.erb
<h1>Contact Me</h1>
<%= link_to "Home", root_path %>

app/views/pages/event_tracker.html.erb
<h1>Event Tracker</h1>
<%= link_to 'People', people_path %>
<%= link_to 'Events', events_path %>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<h1>Niklas Bergstrom - BergstromDomain - Main App</h1>

<%= link_to "About Me", about_path %>
<%= link_to "Contact Me", contact_path %>
<%= link_to "Event Tracker", event_tracker_path %>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<% @people.each do |person| %>
  <p><%= link_to "#{person.first_name} #{person.last_name}", person_path(person) %></p>
  <%= image_tag person.thumb_image %>
<% end %>

<br>

<%= link_to 'New Person', new_person_path %>
<%= link_to "Event Tracker", event_tracker_path %>
<%= link_to "Home", root_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>


<%= image_tag @person.main_image %>


<br>


<%= link_to 'Edit Person', edit_person_path(@person) %> |
<%= link_to "Delete Person", person_path(@person), method: :delete, data: { confirm: "Are you sure you want to delete the person?" } %> |
<%= link_to 'Back', people_path %> |
<%= link_to "Home", root_path %>